---
- name: Require Ansible version
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
  ansible.builtin.include_tasks: tasks/version.yml

- name: Gather facts manually
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
  ansible.builtin.setup:

- name: Get PIF param values
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  ansible.builtin.command: >-
    xe pif-list --minimal params={{ item }} IP={{ ansible_host }}
  loop:
    # IMPORTANT! the set facts task below
    # relies on the order of these items
    - uuid
    - host-uuid
    - host-name-label
    - DNS
    - other-config
  # this task could take a while when there
  # are busy workloads running on the hosts
  timeout: 60
  register: pif_params
  changed_when: false

- name: Get existing host name
  ansible.builtin.command: hostname
  register: hostname_output
  changed_when: false

- name: Get UUIDs of SRs
  run_once: true
  ansible.builtin.command: >-
    xe sr-list --minimal params=uuid name-label='{{ item }}'
  loop:
    - Backup storage
  register: sr_uuids
  changed_when: false

- name: Set facts from params
  vars:
    csv3: "{{ pif_params.results[3].stdout }}"
    csv4: "{{ (pif_params.results[4].stdout |
      regex_search('domain: ([^;]+)','\\1') or ['']) | first }}"
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
  ansible.builtin.set_fact:
    xcp_pif_uuid: "{{ pif_params.results[0].stdout }}"
    xcp_host_uuid: "{{ pif_params.results[1].stdout }}"
    xcp_host_name_xe: "{{ pif_params.results[2].stdout }}"
    xcp_host_name_os: "{{ hostname_output.stdout }}"
    # NOTE: xe --minimal returns CSV delimited by backslash-comma
    xcp_name_servers: "{{ csv3 | split('\\,') if csv3 else [] }}"
    xcp_search_domains: "{{ csv4 | split('\\,') if csv4 else [] }}"
    backup_sr_uuid: "{{ sr_uuids.results[0].stdout }}"

- name: Print gathered facts
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
  ansible.builtin.debug:
    msg: |-
      xcp_pif_uuid: "{{ xcp_pif_uuid }}"
      xcp_host_uuid: "{{ xcp_host_uuid }}"
      xcp_host_name_xe: "{{ xcp_host_name_xe }}"
      xcp_host_name_os: "{{ xcp_host_name_os }}"
      xcp_name_servers: "{{ xcp_name_servers | join(',') }}"
      xcp_search_domains: "{{ xcp_search_domains | join(',') }}"
      backup_sr_uuid: "{{ backup_sr_uuid }}"
