ansible_user: root
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html
ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/{{
                                  lookup('ansible.builtin.env', 'USER') }}.pem"
ansible_ssh_common_args: -o StrictHostKeyChecking=no
# ansible_ssh_password: {vault.yml}

ansible_python_interpreter: /usr/bin/python3
