# Only Python 3.6 is available on XCP-ng 8.2, which causes
# "SyntaxError: future feature annotations is not defined"
# when gathering facts using ansible-core >= 2.17. See:
# https://github.com/ansible/ansible/issues/82068#issuecomment-2123559913
---
- name: Check Ansible version
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html
  ansible.builtin.assert:
    that:
      # https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html
      - ansible_version.full is version('2.17','<')
    success_msg: |-
      Using supportd Ansible version: {{ ansible_version.full }}.
    fail_msg: |-
      Ansible version {{ ansible_version.full }} is not supported!
      This playbook requires "ansible < 10" (ansible-core < 2.17),
      which can be installed via pip: pip3 install "ansible < 10"
  run_once: true
