---
- name: Ensure Python 3 is installed
  hosts: xcphosts
  gather_facts: false # skip because it requires Python
  become: true
  vars:
    # "yum search python3" shows python36
    # is available on XCP-ng version 8.2.
    python3_version: 3.6
    python3_package: python{{ python3_version | replace('.','') }}
    python3_path: /usr/bin/{{ python3_package }}
  pre_tasks:
    - name: Check if Python 3 is installed
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/raw_module.html
      ansible.builtin.raw: "{{ python3_path }} --version"
      register: check_result
      ignore_errors: true
      changed_when: false
  tasks:
    - name: Install YUM package "{{ python3_package }}"
      ansible.builtin.raw: yum install -y {{ python3_package }}
      when: check_result.rc != 0
      changed_when: true

    # - name: Add EPEL repository
    #   # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
    #   ansible.builtin.yum_repository:
    #     name: epel
    #     state: present

    #   when: check_result.rc != 0
    # - name: Install Python 3
    #   # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
    #   ansible.builtin.package:
    #     name: "{{ python3_package }}"
    #     state: present
    #   when: check_result.rc != 0

    - name: Link python3 to {{ python3_path }}
      ansible.builtin.raw: |-
        update-alternatives --install /usr/bin/python3 python3 {{ python3_path }} 1
      when: check_result.rc != 0
      changed_when: true
